services:
  # Backend API
  face-recognition-brain-api:
    container_name: backend
    build: ./
    command: npm run start:dev
    working_dir: /usr/src/face-recognition-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/face-recognition-brain-docker
    links:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/face-recognition-brain-api

  # Postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face-recognition-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - '5432:5432'
